feat: add optionbuttons to app
wixplosives/fundux pull request #5
Opened 2024-04-11 12:23 UTC by DorMosheZarka

Introduced the OptionButtons component to the application, offering users interactive sorting and filtering capabilities. This addition aims to enhance user navigation and improve access to content, although the buttons are currently placeholders without functionality.

2024-04-16 15:00 UTC, noammu requested changes
This PR is almost empty... 🙃 (you also probably forgot to merge from main 😉 )

2024-04-17 10:37 UTC, noammu requested changes

2024-04-17 10:37 UTC, noammu commented on src/components/SortByButton/SortByButton.module.css
> +   border-radius: 0.7em;
In borders we use pixels.
Just a reminder to see the video about px and em

2024-04-17 10:37 UTC, noammu commented on src/components/SortByButton/SortByButton.module.css
> +   background-color: white;
Are this 2 needed?

2024-04-17 10:37 UTC, noammu commented on src/components/SortByButton/SortByButton.module.css
> +}
In the future, are you going to give each kind of option-button margin-right just so you have a... ```gap``` between them?

2024-04-17 10:37 UTC, noammu commented on src/components/OptionButtons/OptionButtons.tsx
> +export default OptionButtons;
In general, this approach is ok.
But what will happen if in the future you will add more option buttons (that you currently don't think about them)?
Will need to go over each one of the buttons and change their style just so you could add the extra button well?
What about if this component was mainly just a wrapper which defines the spacing of this area in relation to other areas, and also the spacing to have between the buttons (like with a gap)?

2024-04-17 10:37 UTC, noammu commented on src/components/OptionButtons/OptionButtons.tsx
> +export default OptionButtons;
Another idea is, what if someone would want to have this component, but without one of the buttons that this component will have? 
How can you solve this problem? (generalize the component, children props 😉 )

2024-04-17 10:37 UTC, noammu commented on src/components/SortByButton/SortByButton.tsx
> +export default SortByButton;
NICE!

2024-04-17 10:56 UTC, DorMosheZarka commented on src/components/SortByButton/SortByButton.module.css
> +   background-color: white;
Its hard to see but the default is transparent. Apparently, display: flex of each list item cancel the list bullets...Thanks!

2024-04-18 07:39 UTC, noammu requested changes

2024-04-18 07:39 UTC, noammu commented on src/components/OptionButtons/OptionButtons.tsx
> +export default OptionButtons;
This is ok.
But in the future you would probably have multiple props, and then writing it like this wouldn't look great to say the least.
How about we change it to ```interface```? Would be a good exercise and we have tons of them in Codux :)

2024-04-18 07:39 UTC, noammu commented on src/components/SortByButton/SortByButton.module.css
> +}
Is the ```font-weight``` needed? my ui eyes are not the best so you tell me 😆

2024-04-18 07:39 UTC, noammu commented on src/components/SortByButton/SortByButton.tsx
> +         {isOpen && (
Why use ```<span>```?

2024-04-18 07:54 UTC, DorMosheZarka commented on src/components/SortByButton/SortByButton.module.css
> +}
indeed, it is necessary, but I've moved it to optionItems for better readability.

2024-04-18 08:10 UTC, noammu approved these changes
Noice

2024-04-18 08:27 UTC, merged